name: Auto Merge PRs

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Automerge
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_RETRIES: 6
